name: Hello world
on: push
jobs:
  my-jobs:
     runs-on: ubuntu-latest
     steps:
     - name: my-step
       run: echo "Hello World!"
  updated-job:
     runs-on: ubuntu-latest
     needs: my-jobs
     steps:
       - name: new-step
         run: echo "Bye"
